<?php

declare(strict_types=1);

namespace ParisBouge\Enum;

use MyCLabs\Enum\Enum;

/**
 * @method static CountryAlpha3 AFGHANISTAN()
 * @method static CountryAlpha3 AALAND_ISLANDS()
 * @method static CountryAlpha3 ALBANIA()
 * @method static CountryAlpha3 ALGERIA()
 * @method static CountryAlpha3 AMERICAN_SAMOA()
 * @method static CountryAlpha3 ANDORRA()
 * @method static CountryAlpha3 ANGOLA()
 * @method static CountryAlpha3 ANGUILLA()
 * @method static CountryAlpha3 ANTARCTICA()
 * @method static CountryAlpha3 ANTIGUA_BARBUDA()
 * @method static CountryAlpha3 ARGENTINA()
 * @method static CountryAlpha3 ARMENIA()
 * @method static CountryAlpha3 ARUBA()
 * @method static CountryAlpha3 AUSTRALIA()
 * @method static CountryAlpha3 AUSTRIA()
 * @method static CountryAlpha3 AZERBAIJAN()
 * @method static CountryAlpha3 BAHAMAS()
 * @method static CountryAlpha3 BAHRAIN()
 * @method static CountryAlpha3 BANGLADESH()
 * @method static CountryAlpha3 BARBADOS()
 * @method static CountryAlpha3 BELARUS()
 * @method static CountryAlpha3 BELGIUM()
 * @method static CountryAlpha3 BELIZE()
 * @method static CountryAlpha3 BENIN()
 * @method static CountryAlpha3 BERMUDA()
 * @method static CountryAlpha3 BHUTAN()
 * @method static CountryAlpha3 BOLIVIA()
 * @method static CountryAlpha3 BOSNIA_HERZEGOVINA()
 * @method static CountryAlpha3 BOTSWANA()
 * @method static CountryAlpha3 BOUVET_ISLAND()
 * @method static CountryAlpha3 BRAZIL()
 * @method static CountryAlpha3 BRITISH_INDIAN_OCEAN_TERRITORY()
 * @method static CountryAlpha3 BRITISH_VIRGIN_ISLANDS()
 * @method static CountryAlpha3 BRUNEI()
 * @method static CountryAlpha3 BULGARIA()
 * @method static CountryAlpha3 BURKINA_FASO()
 * @method static CountryAlpha3 BURUNDI()
 * @method static CountryAlpha3 CAMBODIA()
 * @method static CountryAlpha3 CAMEROON()
 * @method static CountryAlpha3 CANADA()
 * @method static CountryAlpha3 CAPE_VERDE()
 * @method static CountryAlpha3 CARIBBEAN_NETHERLANDS()
 * @method static CountryAlpha3 CAYMAN_ISLANDS()
 * @method static CountryAlpha3 CENTRAL_AFRICAN_REPUBLIC()
 * @method static CountryAlpha3 CHAD()
 * @method static CountryAlpha3 CHILE()
 * @method static CountryAlpha3 CHINA()
 * @method static CountryAlpha3 CHRISTMAS_ISLAND()
 * @method static CountryAlpha3 COCOS_KEELING_ISLANDS()
 * @method static CountryAlpha3 COLOMBIA()
 * @method static CountryAlpha3 COMOROS()
 * @method static CountryAlpha3 CONGO_BRAZZAVILLE()
 * @method static CountryAlpha3 CONGO_KINSHASA()
 * @method static CountryAlpha3 COOK_ISLANDS()
 * @method static CountryAlpha3 COSTA_RICA()
 * @method static CountryAlpha3 COTE_D_IVOIRE()
 * @method static CountryAlpha3 CROATIA()
 * @method static CountryAlpha3 CUBA()
 * @method static CountryAlpha3 CURACAO()
 * @method static CountryAlpha3 CYPRUS()
 * @method static CountryAlpha3 CZECHIA()
 * @method static CountryAlpha3 DENMARK()
 * @method static CountryAlpha3 DJIBOUTI()
 * @method static CountryAlpha3 DOMINICA()
 * @method static CountryAlpha3 DOMINICAN_REPUBLIC()
 * @method static CountryAlpha3 ECUADOR()
 * @method static CountryAlpha3 EGYPT()
 * @method static CountryAlpha3 EL_SALVADOR()
 * @method static CountryAlpha3 EQUATORIAL_GUINEA()
 * @method static CountryAlpha3 ERITREA()
 * @method static CountryAlpha3 ESTONIA()
 * @method static CountryAlpha3 ESWATINI()
 * @method static CountryAlpha3 ETHIOPIA()
 * @method static CountryAlpha3 FALKLAND_ISLANDS()
 * @method static CountryAlpha3 FAROE_ISLANDS()
 * @method static CountryAlpha3 FIJI()
 * @method static CountryAlpha3 FINLAND()
 * @method static CountryAlpha3 FRANCE()
 * @method static CountryAlpha3 FRENCH_GUIANA()
 * @method static CountryAlpha3 FRENCH_POLYNESIA()
 * @method static CountryAlpha3 FRENCH_SOUTHERN_TERRITORIES()
 * @method static CountryAlpha3 GABON()
 * @method static CountryAlpha3 GAMBIA()
 * @method static CountryAlpha3 GEORGIA()
 * @method static CountryAlpha3 GERMANY()
 * @method static CountryAlpha3 GHANA()
 * @method static CountryAlpha3 GIBRALTAR()
 * @method static CountryAlpha3 GREECE()
 * @method static CountryAlpha3 GREENLAND()
 * @method static CountryAlpha3 GRENADA()
 * @method static CountryAlpha3 GUADELOUPE()
 * @method static CountryAlpha3 GUAM()
 * @method static CountryAlpha3 GUATEMALA()
 * @method static CountryAlpha3 GUERNSEY()
 * @method static CountryAlpha3 GUINEA()
 * @method static CountryAlpha3 GUINEA_BISSAU()
 * @method static CountryAlpha3 GUYANA()
 * @method static CountryAlpha3 HAITI()
 * @method static CountryAlpha3 HEARD_MCDONALD_ISLANDS()
 * @method static CountryAlpha3 HONDURAS()
 * @method static CountryAlpha3 HONG_KONG_SAR_CHINA()
 * @method static CountryAlpha3 HUNGARY()
 * @method static CountryAlpha3 ICELAND()
 * @method static CountryAlpha3 INDIA()
 * @method static CountryAlpha3 INDONESIA()
 * @method static CountryAlpha3 IRAN()
 * @method static CountryAlpha3 IRAQ()
 * @method static CountryAlpha3 IRELAND()
 * @method static CountryAlpha3 ISLE_OF_MAN()
 * @method static CountryAlpha3 ISRAEL()
 * @method static CountryAlpha3 ITALY()
 * @method static CountryAlpha3 JAMAICA()
 * @method static CountryAlpha3 JAPAN()
 * @method static CountryAlpha3 JERSEY()
 * @method static CountryAlpha3 JORDAN()
 * @method static CountryAlpha3 KAZAKHSTAN()
 * @method static CountryAlpha3 KENYA()
 * @method static CountryAlpha3 KIRIBATI()
 * @method static CountryAlpha3 KUWAIT()
 * @method static CountryAlpha3 KYRGYZSTAN()
 * @method static CountryAlpha3 LAOS()
 * @method static CountryAlpha3 LATVIA()
 * @method static CountryAlpha3 LEBANON()
 * @method static CountryAlpha3 LESOTHO()
 * @method static CountryAlpha3 LIBERIA()
 * @method static CountryAlpha3 LIBYA()
 * @method static CountryAlpha3 LIECHTENSTEIN()
 * @method static CountryAlpha3 LITHUANIA()
 * @method static CountryAlpha3 LUXEMBOURG()
 * @method static CountryAlpha3 MACAO_SAR_CHINA()
 * @method static CountryAlpha3 MADAGASCAR()
 * @method static CountryAlpha3 MALAWI()
 * @method static CountryAlpha3 MALAYSIA()
 * @method static CountryAlpha3 MALDIVES()
 * @method static CountryAlpha3 MALI()
 * @method static CountryAlpha3 MALTA()
 * @method static CountryAlpha3 MARSHALL_ISLANDS()
 * @method static CountryAlpha3 MARTINIQUE()
 * @method static CountryAlpha3 MAURITANIA()
 * @method static CountryAlpha3 MAURITIUS()
 * @method static CountryAlpha3 MAYOTTE()
 * @method static CountryAlpha3 MEXICO()
 * @method static CountryAlpha3 MICRONESIA()
 * @method static CountryAlpha3 MOLDOVA()
 * @method static CountryAlpha3 MONACO()
 * @method static CountryAlpha3 MONGOLIA()
 * @method static CountryAlpha3 MONTENEGRO()
 * @method static CountryAlpha3 MONTSERRAT()
 * @method static CountryAlpha3 MOROCCO()
 * @method static CountryAlpha3 MOZAMBIQUE()
 * @method static CountryAlpha3 MYANMAR_BURMA()
 * @method static CountryAlpha3 NAMIBIA()
 * @method static CountryAlpha3 NAURU()
 * @method static CountryAlpha3 NEPAL()
 * @method static CountryAlpha3 NETHERLANDS()
 * @method static CountryAlpha3 NEW_CALEDONIA()
 * @method static CountryAlpha3 NEW_ZEALAND()
 * @method static CountryAlpha3 NICARAGUA()
 * @method static CountryAlpha3 NIGER()
 * @method static CountryAlpha3 NIGERIA()
 * @method static CountryAlpha3 NIUE()
 * @method static CountryAlpha3 NORFOLK_ISLAND()
 * @method static CountryAlpha3 NORTH_KOREA()
 * @method static CountryAlpha3 NORTH_MACEDONIA()
 * @method static CountryAlpha3 NORTHERN_MARIANA_ISLANDS()
 * @method static CountryAlpha3 NORWAY()
 * @method static CountryAlpha3 OMAN()
 * @method static CountryAlpha3 PAKISTAN()
 * @method static CountryAlpha3 PALAU()
 * @method static CountryAlpha3 PALESTINIAN_TERRITORIES()
 * @method static CountryAlpha3 PANAMA()
 * @method static CountryAlpha3 PAPUA_NEW_GUINEA()
 * @method static CountryAlpha3 PARAGUAY()
 * @method static CountryAlpha3 PERU()
 * @method static CountryAlpha3 PHILIPPINES()
 * @method static CountryAlpha3 PITCAIRN_ISLANDS()
 * @method static CountryAlpha3 POLAND()
 * @method static CountryAlpha3 PORTUGAL()
 * @method static CountryAlpha3 PUERTO_RICO()
 * @method static CountryAlpha3 QATAR()
 * @method static CountryAlpha3 REUNION()
 * @method static CountryAlpha3 ROMANIA()
 * @method static CountryAlpha3 RUSSIA()
 * @method static CountryAlpha3 RWANDA()
 * @method static CountryAlpha3 SAMOA()
 * @method static CountryAlpha3 SAN_MARINO()
 * @method static CountryAlpha3 SAO_TOME_PRINCIPE()
 * @method static CountryAlpha3 SAUDI_ARABIA()
 * @method static CountryAlpha3 SENEGAL()
 * @method static CountryAlpha3 SERBIA()
 * @method static CountryAlpha3 SEYCHELLES()
 * @method static CountryAlpha3 SIERRA_LEONE()
 * @method static CountryAlpha3 SINGAPORE()
 * @method static CountryAlpha3 SINT_MAARTEN()
 * @method static CountryAlpha3 SLOVAKIA()
 * @method static CountryAlpha3 SLOVENIA()
 * @method static CountryAlpha3 SOLOMON_ISLANDS()
 * @method static CountryAlpha3 SOMALIA()
 * @method static CountryAlpha3 SOUTH_AFRICA()
 * @method static CountryAlpha3 SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS()
 * @method static CountryAlpha3 SOUTH_KOREA()
 * @method static CountryAlpha3 SOUTH_SUDAN()
 * @method static CountryAlpha3 SPAIN()
 * @method static CountryAlpha3 SRI_LANKA()
 * @method static CountryAlpha3 ST_BARTHELEMY()
 * @method static CountryAlpha3 ST_HELENA()
 * @method static CountryAlpha3 ST_KITTS_NEVIS()
 * @method static CountryAlpha3 ST_LUCIA()
 * @method static CountryAlpha3 ST_MARTIN()
 * @method static CountryAlpha3 ST_PIERRE_MIQUELON()
 * @method static CountryAlpha3 ST_VINCENT_GRENADINES()
 * @method static CountryAlpha3 SUDAN()
 * @method static CountryAlpha3 SURINAME()
 * @method static CountryAlpha3 SVALBARD_JAN_MAYEN()
 * @method static CountryAlpha3 SWEDEN()
 * @method static CountryAlpha3 SWITZERLAND()
 * @method static CountryAlpha3 SYRIA()
 * @method static CountryAlpha3 TAIWAN()
 * @method static CountryAlpha3 TAJIKISTAN()
 * @method static CountryAlpha3 TANZANIA()
 * @method static CountryAlpha3 THAILAND()
 * @method static CountryAlpha3 TIMOR_LESTE()
 * @method static CountryAlpha3 TOGO()
 * @method static CountryAlpha3 TOKELAU()
 * @method static CountryAlpha3 TONGA()
 * @method static CountryAlpha3 TRINIDAD_TOBAGO()
 * @method static CountryAlpha3 TUNISIA()
 * @method static CountryAlpha3 TURKEY()
 * @method static CountryAlpha3 TURKMENISTAN()
 * @method static CountryAlpha3 TURKS_CAICOS_ISLANDS()
 * @method static CountryAlpha3 TUVALU()
 * @method static CountryAlpha3 U_S_OUTLYING_ISLANDS()
 * @method static CountryAlpha3 U_S_VIRGIN_ISLANDS()
 * @method static CountryAlpha3 UGANDA()
 * @method static CountryAlpha3 UKRAINE()
 * @method static CountryAlpha3 UNITED_ARAB_EMIRATES()
 * @method static CountryAlpha3 UNITED_KINGDOM()
 * @method static CountryAlpha3 UNITED_STATES()
 * @method static CountryAlpha3 URUGUAY()
 * @method static CountryAlpha3 UZBEKISTAN()
 * @method static CountryAlpha3 VANUATU()
 * @method static CountryAlpha3 VATICAN_CITY()
 * @method static CountryAlpha3 VENEZUELA()
 * @method static CountryAlpha3 VIETNAM()
 * @method static CountryAlpha3 WALLIS_FUTUNA()
 * @method static CountryAlpha3 WESTERN_SAHARA()
 * @method static CountryAlpha3 YEMEN()
 * @method static CountryAlpha3 ZAMBIA()
 * @method static CountryAlpha3 ZIMBABWE()
 */
class CountryAlpha3 extends Enum
{
    private const AFGHANISTAN = 'AFG';
    private const AALAND_ISLANDS = 'ALA';
    private const ALBANIA = 'ALB';
    private const ALGERIA = 'DZA';
    private const AMERICAN_SAMOA = 'ASM';
    private const ANDORRA = 'AND';
    private const ANGOLA = 'AGO';
    private const ANGUILLA = 'AIA';
    private const ANTARCTICA = 'ATA';
    private const ANTIGUA_BARBUDA = 'ATG';
    private const ARGENTINA = 'ARG';
    private const ARMENIA = 'ARM';
    private const ARUBA = 'ABW';
    private const AUSTRALIA = 'AUS';
    private const AUSTRIA = 'AUT';
    private const AZERBAIJAN = 'AZE';
    private const BAHAMAS = 'BHS';
    private const BAHRAIN = 'BHR';
    private const BANGLADESH = 'BGD';
    private const BARBADOS = 'BRB';
    private const BELARUS = 'BLR';
    private const BELGIUM = 'BEL';
    private const BELIZE = 'BLZ';
    private const BENIN = 'BEN';
    private const BERMUDA = 'BMU';
    private const BHUTAN = 'BTN';
    private const BOLIVIA = 'BOL';
    private const BOSNIA_HERZEGOVINA = 'BIH';
    private const BOTSWANA = 'BWA';
    private const BOUVET_ISLAND = 'BVT';
    private const BRAZIL = 'BRA';
    private const BRITISH_INDIAN_OCEAN_TERRITORY = 'IOT';
    private const BRITISH_VIRGIN_ISLANDS = 'VGB';
    private const BRUNEI = 'BRN';
    private const BULGARIA = 'BGR';
    private const BURKINA_FASO = 'BFA';
    private const BURUNDI = 'BDI';
    private const CAMBODIA = 'KHM';
    private const CAMEROON = 'CMR';
    private const CANADA = 'CAN';
    private const CAPE_VERDE = 'CPV';
    private const CARIBBEAN_NETHERLANDS = 'BES';
    private const CAYMAN_ISLANDS = 'CYM';
    private const CENTRAL_AFRICAN_REPUBLIC = 'CAF';
    private const CHAD = 'TCD';
    private const CHILE = 'CHL';
    private const CHINA = 'CHN';
    private const CHRISTMAS_ISLAND = 'CXR';
    private const COCOS_KEELING_ISLANDS = 'CCK';
    private const COLOMBIA = 'COL';
    private const COMOROS = 'COM';
    private const CONGO_BRAZZAVILLE = 'COG';
    private const CONGO_KINSHASA = 'COD';
    private const COOK_ISLANDS = 'COK';
    private const COSTA_RICA = 'CRI';
    private const COTE_D_IVOIRE = 'CIV';
    private const CROATIA = 'HRV';
    private const CUBA = 'CUB';
    private const CURACAO = 'CUW';
    private const CYPRUS = 'CYP';
    private const CZECHIA = 'CZE';
    private const DENMARK = 'DNK';
    private const DJIBOUTI = 'DJI';
    private const DOMINICA = 'DMA';
    private const DOMINICAN_REPUBLIC = 'DOM';
    private const ECUADOR = 'ECU';
    private const EGYPT = 'EGY';
    private const EL_SALVADOR = 'SLV';
    private const EQUATORIAL_GUINEA = 'GNQ';
    private const ERITREA = 'ERI';
    private const ESTONIA = 'EST';
    private const ESWATINI = 'SWZ';
    private const ETHIOPIA = 'ETH';
    private const FALKLAND_ISLANDS = 'FLK';
    private const FAROE_ISLANDS = 'FRO';
    private const FIJI = 'FJI';
    private const FINLAND = 'FIN';
    private const FRANCE = 'FRA';
    private const FRENCH_GUIANA = 'GUF';
    private const FRENCH_POLYNESIA = 'PYF';
    private const FRENCH_SOUTHERN_TERRITORIES = 'ATF';
    private const GABON = 'GAB';
    private const GAMBIA = 'GMB';
    private const GEORGIA = 'GEO';
    private const GERMANY = 'DEU';
    private const GHANA = 'GHA';
    private const GIBRALTAR = 'GIB';
    private const GREECE = 'GRC';
    private const GREENLAND = 'GRL';
    private const GRENADA = 'GRD';
    private const GUADELOUPE = 'GLP';
    private const GUAM = 'GUM';
    private const GUATEMALA = 'GTM';
    private const GUERNSEY = 'GGY';
    private const GUINEA = 'GIN';
    private const GUINEA_BISSAU = 'GNB';
    private const GUYANA = 'GUY';
    private const HAITI = 'HTI';
    private const HEARD_MCDONALD_ISLANDS = 'HMD';
    private const HONDURAS = 'HND';
    private const HONG_KONG_SAR_CHINA = 'HKG';
    private const HUNGARY = 'HUN';
    private const ICELAND = 'ISL';
    private const INDIA = 'IND';
    private const INDONESIA = 'IDN';
    private const IRAN = 'IRN';
    private const IRAQ = 'IRQ';
    private const IRELAND = 'IRL';
    private const ISLE_OF_MAN = 'IMN';
    private const ISRAEL = 'ISR';
    private const ITALY = 'ITA';
    private const JAMAICA = 'JAM';
    private const JAPAN = 'JPN';
    private const JERSEY = 'JEY';
    private const JORDAN = 'JOR';
    private const KAZAKHSTAN = 'KAZ';
    private const KENYA = 'KEN';
    private const KIRIBATI = 'KIR';
    private const KUWAIT = 'KWT';
    private const KYRGYZSTAN = 'KGZ';
    private const LAOS = 'LAO';
    private const LATVIA = 'LVA';
    private const LEBANON = 'LBN';
    private const LESOTHO = 'LSO';
    private const LIBERIA = 'LBR';
    private const LIBYA = 'LBY';
    private const LIECHTENSTEIN = 'LIE';
    private const LITHUANIA = 'LTU';
    private const LUXEMBOURG = 'LUX';
    private const MACAO_SAR_CHINA = 'MAC';
    private const MADAGASCAR = 'MDG';
    private const MALAWI = 'MWI';
    private const MALAYSIA = 'MYS';
    private const MALDIVES = 'MDV';
    private const MALI = 'MLI';
    private const MALTA = 'MLT';
    private const MARSHALL_ISLANDS = 'MHL';
    private const MARTINIQUE = 'MTQ';
    private const MAURITANIA = 'MRT';
    private const MAURITIUS = 'MUS';
    private const MAYOTTE = 'MYT';
    private const MEXICO = 'MEX';
    private const MICRONESIA = 'FSM';
    private const MOLDOVA = 'MDA';
    private const MONACO = 'MCO';
    private const MONGOLIA = 'MNG';
    private const MONTENEGRO = 'MNE';
    private const MONTSERRAT = 'MSR';
    private const MOROCCO = 'MAR';
    private const MOZAMBIQUE = 'MOZ';
    private const MYANMAR_BURMA = 'MMR';
    private const NAMIBIA = 'NAM';
    private const NAURU = 'NRU';
    private const NEPAL = 'NPL';
    private const NETHERLANDS = 'NLD';
    private const NEW_CALEDONIA = 'NCL';
    private const NEW_ZEALAND = 'NZL';
    private const NICARAGUA = 'NIC';
    private const NIGER = 'NER';
    private const NIGERIA = 'NGA';
    private const NIUE = 'NIU';
    private const NORFOLK_ISLAND = 'NFK';
    private const NORTH_KOREA = 'PRK';
    private const NORTH_MACEDONIA = 'MKD';
    private const NORTHERN_MARIANA_ISLANDS = 'MNP';
    private const NORWAY = 'NOR';
    private const OMAN = 'OMN';
    private const PAKISTAN = 'PAK';
    private const PALAU = 'PLW';
    private const PALESTINIAN_TERRITORIES = 'PSE';
    private const PANAMA = 'PAN';
    private const PAPUA_NEW_GUINEA = 'PNG';
    private const PARAGUAY = 'PRY';
    private const PERU = 'PER';
    private const PHILIPPINES = 'PHL';
    private const PITCAIRN_ISLANDS = 'PCN';
    private const POLAND = 'POL';
    private const PORTUGAL = 'PRT';
    private const PUERTO_RICO = 'PRI';
    private const QATAR = 'QAT';
    private const REUNION = 'REU';
    private const ROMANIA = 'ROU';
    private const RUSSIA = 'RUS';
    private const RWANDA = 'RWA';
    private const SAMOA = 'WSM';
    private const SAN_MARINO = 'SMR';
    private const SAO_TOME_PRINCIPE = 'STP';
    private const SAUDI_ARABIA = 'SAU';
    private const SENEGAL = 'SEN';
    private const SERBIA = 'SRB';
    private const SEYCHELLES = 'SYC';
    private const SIERRA_LEONE = 'SLE';
    private const SINGAPORE = 'SGP';
    private const SINT_MAARTEN = 'SXM';
    private const SLOVAKIA = 'SVK';
    private const SLOVENIA = 'SVN';
    private const SOLOMON_ISLANDS = 'SLB';
    private const SOMALIA = 'SOM';
    private const SOUTH_AFRICA = 'ZAF';
    private const SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS = 'SGS';
    private const SOUTH_KOREA = 'KOR';
    private const SOUTH_SUDAN = 'SSD';
    private const SPAIN = 'ESP';
    private const SRI_LANKA = 'LKA';
    private const ST_BARTHELEMY = 'BLM';
    private const ST_HELENA = 'SHN';
    private const ST_KITTS_NEVIS = 'KNA';
    private const ST_LUCIA = 'LCA';
    private const ST_MARTIN = 'MAF';
    private const ST_PIERRE_MIQUELON = 'SPM';
    private const ST_VINCENT_GRENADINES = 'VCT';
    private const SUDAN = 'SDN';
    private const SURINAME = 'SUR';
    private const SVALBARD_JAN_MAYEN = 'SJM';
    private const SWEDEN = 'SWE';
    private const SWITZERLAND = 'CHE';
    private const SYRIA = 'SYR';
    private const TAIWAN = 'TWN';
    private const TAJIKISTAN = 'TJK';
    private const TANZANIA = 'TZA';
    private const THAILAND = 'THA';
    private const TIMOR_LESTE = 'TLS';
    private const TOGO = 'TGO';
    private const TOKELAU = 'TKL';
    private const TONGA = 'TON';
    private const TRINIDAD_TOBAGO = 'TTO';
    private const TUNISIA = 'TUN';
    private const TURKEY = 'TUR';
    private const TURKMENISTAN = 'TKM';
    private const TURKS_CAICOS_ISLANDS = 'TCA';
    private const TUVALU = 'TUV';
    private const U_S_OUTLYING_ISLANDS = 'UMI';
    private const U_S_VIRGIN_ISLANDS = 'VIR';
    private const UGANDA = 'UGA';
    private const UKRAINE = 'UKR';
    private const UNITED_ARAB_EMIRATES = 'ARE';
    private const UNITED_KINGDOM = 'GBR';
    private const UNITED_STATES = 'USA';
    private const URUGUAY = 'URY';
    private const UZBEKISTAN = 'UZB';
    private const VANUATU = 'VUT';
    private const VATICAN_CITY = 'VAT';
    private const VENEZUELA = 'VEN';
    private const VIETNAM = 'VNM';
    private const WALLIS_FUTUNA = 'WLF';
    private const WESTERN_SAHARA = 'ESH';
    private const YEMEN = 'YEM';
    private const ZAMBIA = 'ZMB';
    private const ZIMBABWE = 'ZWE';
}
