<?php

declare(strict_types=1);

namespace ParisBouge\Enum;

use MyCLabs\Enum\Enum;

/**
 * @method static CountryAlpha2 AFGHANISTAN()
 * @method static CountryAlpha2 AALAND_ISLANDS()
 * @method static CountryAlpha2 ALBANIA()
 * @method static CountryAlpha2 ALGERIA()
 * @method static CountryAlpha2 AMERICAN_SAMOA()
 * @method static CountryAlpha2 ANDORRA()
 * @method static CountryAlpha2 ANGOLA()
 * @method static CountryAlpha2 ANGUILLA()
 * @method static CountryAlpha2 ANTARCTICA()
 * @method static CountryAlpha2 ANTIGUA_BARBUDA()
 * @method static CountryAlpha2 ARGENTINA()
 * @method static CountryAlpha2 ARMENIA()
 * @method static CountryAlpha2 ARUBA()
 * @method static CountryAlpha2 AUSTRALIA()
 * @method static CountryAlpha2 AUSTRIA()
 * @method static CountryAlpha2 AZERBAIJAN()
 * @method static CountryAlpha2 BAHAMAS()
 * @method static CountryAlpha2 BAHRAIN()
 * @method static CountryAlpha2 BANGLADESH()
 * @method static CountryAlpha2 BARBADOS()
 * @method static CountryAlpha2 BELARUS()
 * @method static CountryAlpha2 BELGIUM()
 * @method static CountryAlpha2 BELIZE()
 * @method static CountryAlpha2 BENIN()
 * @method static CountryAlpha2 BERMUDA()
 * @method static CountryAlpha2 BHUTAN()
 * @method static CountryAlpha2 BOLIVIA()
 * @method static CountryAlpha2 BOSNIA_HERZEGOVINA()
 * @method static CountryAlpha2 BOTSWANA()
 * @method static CountryAlpha2 BOUVET_ISLAND()
 * @method static CountryAlpha2 BRAZIL()
 * @method static CountryAlpha2 BRITISH_INDIAN_OCEAN_TERRITORY()
 * @method static CountryAlpha2 BRITISH_VIRGIN_ISLANDS()
 * @method static CountryAlpha2 BRUNEI()
 * @method static CountryAlpha2 BULGARIA()
 * @method static CountryAlpha2 BURKINA_FASO()
 * @method static CountryAlpha2 BURUNDI()
 * @method static CountryAlpha2 CAMBODIA()
 * @method static CountryAlpha2 CAMEROON()
 * @method static CountryAlpha2 CANADA()
 * @method static CountryAlpha2 CAPE_VERDE()
 * @method static CountryAlpha2 CARIBBEAN_NETHERLANDS()
 * @method static CountryAlpha2 CAYMAN_ISLANDS()
 * @method static CountryAlpha2 CENTRAL_AFRICAN_REPUBLIC()
 * @method static CountryAlpha2 CHAD()
 * @method static CountryAlpha2 CHILE()
 * @method static CountryAlpha2 CHINA()
 * @method static CountryAlpha2 CHRISTMAS_ISLAND()
 * @method static CountryAlpha2 COCOS_KEELING_ISLANDS()
 * @method static CountryAlpha2 COLOMBIA()
 * @method static CountryAlpha2 COMOROS()
 * @method static CountryAlpha2 CONGO_BRAZZAVILLE()
 * @method static CountryAlpha2 CONGO_KINSHASA()
 * @method static CountryAlpha2 COOK_ISLANDS()
 * @method static CountryAlpha2 COSTA_RICA()
 * @method static CountryAlpha2 COTE_D_IVOIRE()
 * @method static CountryAlpha2 CROATIA()
 * @method static CountryAlpha2 CUBA()
 * @method static CountryAlpha2 CURACAO()
 * @method static CountryAlpha2 CYPRUS()
 * @method static CountryAlpha2 CZECHIA()
 * @method static CountryAlpha2 DENMARK()
 * @method static CountryAlpha2 DJIBOUTI()
 * @method static CountryAlpha2 DOMINICA()
 * @method static CountryAlpha2 DOMINICAN_REPUBLIC()
 * @method static CountryAlpha2 ECUADOR()
 * @method static CountryAlpha2 EGYPT()
 * @method static CountryAlpha2 EL_SALVADOR()
 * @method static CountryAlpha2 EQUATORIAL_GUINEA()
 * @method static CountryAlpha2 ERITREA()
 * @method static CountryAlpha2 ESTONIA()
 * @method static CountryAlpha2 ESWATINI()
 * @method static CountryAlpha2 ETHIOPIA()
 * @method static CountryAlpha2 FALKLAND_ISLANDS()
 * @method static CountryAlpha2 FAROE_ISLANDS()
 * @method static CountryAlpha2 FIJI()
 * @method static CountryAlpha2 FINLAND()
 * @method static CountryAlpha2 FRANCE()
 * @method static CountryAlpha2 FRENCH_GUIANA()
 * @method static CountryAlpha2 FRENCH_POLYNESIA()
 * @method static CountryAlpha2 FRENCH_SOUTHERN_TERRITORIES()
 * @method static CountryAlpha2 GABON()
 * @method static CountryAlpha2 GAMBIA()
 * @method static CountryAlpha2 GEORGIA()
 * @method static CountryAlpha2 GERMANY()
 * @method static CountryAlpha2 GHANA()
 * @method static CountryAlpha2 GIBRALTAR()
 * @method static CountryAlpha2 GREECE()
 * @method static CountryAlpha2 GREENLAND()
 * @method static CountryAlpha2 GRENADA()
 * @method static CountryAlpha2 GUADELOUPE()
 * @method static CountryAlpha2 GUAM()
 * @method static CountryAlpha2 GUATEMALA()
 * @method static CountryAlpha2 GUERNSEY()
 * @method static CountryAlpha2 GUINEA()
 * @method static CountryAlpha2 GUINEA_BISSAU()
 * @method static CountryAlpha2 GUYANA()
 * @method static CountryAlpha2 HAITI()
 * @method static CountryAlpha2 HEARD_MCDONALD_ISLANDS()
 * @method static CountryAlpha2 HONDURAS()
 * @method static CountryAlpha2 HONG_KONG_SAR_CHINA()
 * @method static CountryAlpha2 HUNGARY()
 * @method static CountryAlpha2 ICELAND()
 * @method static CountryAlpha2 INDIA()
 * @method static CountryAlpha2 INDONESIA()
 * @method static CountryAlpha2 IRAN()
 * @method static CountryAlpha2 IRAQ()
 * @method static CountryAlpha2 IRELAND()
 * @method static CountryAlpha2 ISLE_OF_MAN()
 * @method static CountryAlpha2 ISRAEL()
 * @method static CountryAlpha2 ITALY()
 * @method static CountryAlpha2 JAMAICA()
 * @method static CountryAlpha2 JAPAN()
 * @method static CountryAlpha2 JERSEY()
 * @method static CountryAlpha2 JORDAN()
 * @method static CountryAlpha2 KAZAKHSTAN()
 * @method static CountryAlpha2 KENYA()
 * @method static CountryAlpha2 KIRIBATI()
 * @method static CountryAlpha2 KUWAIT()
 * @method static CountryAlpha2 KYRGYZSTAN()
 * @method static CountryAlpha2 LAOS()
 * @method static CountryAlpha2 LATVIA()
 * @method static CountryAlpha2 LEBANON()
 * @method static CountryAlpha2 LESOTHO()
 * @method static CountryAlpha2 LIBERIA()
 * @method static CountryAlpha2 LIBYA()
 * @method static CountryAlpha2 LIECHTENSTEIN()
 * @method static CountryAlpha2 LITHUANIA()
 * @method static CountryAlpha2 LUXEMBOURG()
 * @method static CountryAlpha2 MACAO_SAR_CHINA()
 * @method static CountryAlpha2 MADAGASCAR()
 * @method static CountryAlpha2 MALAWI()
 * @method static CountryAlpha2 MALAYSIA()
 * @method static CountryAlpha2 MALDIVES()
 * @method static CountryAlpha2 MALI()
 * @method static CountryAlpha2 MALTA()
 * @method static CountryAlpha2 MARSHALL_ISLANDS()
 * @method static CountryAlpha2 MARTINIQUE()
 * @method static CountryAlpha2 MAURITANIA()
 * @method static CountryAlpha2 MAURITIUS()
 * @method static CountryAlpha2 MAYOTTE()
 * @method static CountryAlpha2 MEXICO()
 * @method static CountryAlpha2 MICRONESIA()
 * @method static CountryAlpha2 MOLDOVA()
 * @method static CountryAlpha2 MONACO()
 * @method static CountryAlpha2 MONGOLIA()
 * @method static CountryAlpha2 MONTENEGRO()
 * @method static CountryAlpha2 MONTSERRAT()
 * @method static CountryAlpha2 MOROCCO()
 * @method static CountryAlpha2 MOZAMBIQUE()
 * @method static CountryAlpha2 MYANMAR_BURMA()
 * @method static CountryAlpha2 NAMIBIA()
 * @method static CountryAlpha2 NAURU()
 * @method static CountryAlpha2 NEPAL()
 * @method static CountryAlpha2 NETHERLANDS()
 * @method static CountryAlpha2 NEW_CALEDONIA()
 * @method static CountryAlpha2 NEW_ZEALAND()
 * @method static CountryAlpha2 NICARAGUA()
 * @method static CountryAlpha2 NIGER()
 * @method static CountryAlpha2 NIGERIA()
 * @method static CountryAlpha2 NIUE()
 * @method static CountryAlpha2 NORFOLK_ISLAND()
 * @method static CountryAlpha2 NORTH_KOREA()
 * @method static CountryAlpha2 NORTH_MACEDONIA()
 * @method static CountryAlpha2 NORTHERN_MARIANA_ISLANDS()
 * @method static CountryAlpha2 NORWAY()
 * @method static CountryAlpha2 OMAN()
 * @method static CountryAlpha2 PAKISTAN()
 * @method static CountryAlpha2 PALAU()
 * @method static CountryAlpha2 PALESTINIAN_TERRITORIES()
 * @method static CountryAlpha2 PANAMA()
 * @method static CountryAlpha2 PAPUA_NEW_GUINEA()
 * @method static CountryAlpha2 PARAGUAY()
 * @method static CountryAlpha2 PERU()
 * @method static CountryAlpha2 PHILIPPINES()
 * @method static CountryAlpha2 PITCAIRN_ISLANDS()
 * @method static CountryAlpha2 POLAND()
 * @method static CountryAlpha2 PORTUGAL()
 * @method static CountryAlpha2 PUERTO_RICO()
 * @method static CountryAlpha2 QATAR()
 * @method static CountryAlpha2 REUNION()
 * @method static CountryAlpha2 ROMANIA()
 * @method static CountryAlpha2 RUSSIA()
 * @method static CountryAlpha2 RWANDA()
 * @method static CountryAlpha2 SAMOA()
 * @method static CountryAlpha2 SAN_MARINO()
 * @method static CountryAlpha2 SAO_TOME_PRINCIPE()
 * @method static CountryAlpha2 SAUDI_ARABIA()
 * @method static CountryAlpha2 SENEGAL()
 * @method static CountryAlpha2 SERBIA()
 * @method static CountryAlpha2 SEYCHELLES()
 * @method static CountryAlpha2 SIERRA_LEONE()
 * @method static CountryAlpha2 SINGAPORE()
 * @method static CountryAlpha2 SINT_MAARTEN()
 * @method static CountryAlpha2 SLOVAKIA()
 * @method static CountryAlpha2 SLOVENIA()
 * @method static CountryAlpha2 SOLOMON_ISLANDS()
 * @method static CountryAlpha2 SOMALIA()
 * @method static CountryAlpha2 SOUTH_AFRICA()
 * @method static CountryAlpha2 SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS()
 * @method static CountryAlpha2 SOUTH_KOREA()
 * @method static CountryAlpha2 SOUTH_SUDAN()
 * @method static CountryAlpha2 SPAIN()
 * @method static CountryAlpha2 SRI_LANKA()
 * @method static CountryAlpha2 ST_BARTHELEMY()
 * @method static CountryAlpha2 ST_HELENA()
 * @method static CountryAlpha2 ST_KITTS_NEVIS()
 * @method static CountryAlpha2 ST_LUCIA()
 * @method static CountryAlpha2 ST_MARTIN()
 * @method static CountryAlpha2 ST_PIERRE_MIQUELON()
 * @method static CountryAlpha2 ST_VINCENT_GRENADINES()
 * @method static CountryAlpha2 SUDAN()
 * @method static CountryAlpha2 SURINAME()
 * @method static CountryAlpha2 SVALBARD_JAN_MAYEN()
 * @method static CountryAlpha2 SWEDEN()
 * @method static CountryAlpha2 SWITZERLAND()
 * @method static CountryAlpha2 SYRIA()
 * @method static CountryAlpha2 TAIWAN()
 * @method static CountryAlpha2 TAJIKISTAN()
 * @method static CountryAlpha2 TANZANIA()
 * @method static CountryAlpha2 THAILAND()
 * @method static CountryAlpha2 TIMOR_LESTE()
 * @method static CountryAlpha2 TOGO()
 * @method static CountryAlpha2 TOKELAU()
 * @method static CountryAlpha2 TONGA()
 * @method static CountryAlpha2 TRINIDAD_TOBAGO()
 * @method static CountryAlpha2 TUNISIA()
 * @method static CountryAlpha2 TURKEY()
 * @method static CountryAlpha2 TURKMENISTAN()
 * @method static CountryAlpha2 TURKS_CAICOS_ISLANDS()
 * @method static CountryAlpha2 TUVALU()
 * @method static CountryAlpha2 U_S_OUTLYING_ISLANDS()
 * @method static CountryAlpha2 U_S_VIRGIN_ISLANDS()
 * @method static CountryAlpha2 UGANDA()
 * @method static CountryAlpha2 UKRAINE()
 * @method static CountryAlpha2 UNITED_ARAB_EMIRATES()
 * @method static CountryAlpha2 UNITED_KINGDOM()
 * @method static CountryAlpha2 UNITED_STATES()
 * @method static CountryAlpha2 URUGUAY()
 * @method static CountryAlpha2 UZBEKISTAN()
 * @method static CountryAlpha2 VANUATU()
 * @method static CountryAlpha2 VATICAN_CITY()
 * @method static CountryAlpha2 VENEZUELA()
 * @method static CountryAlpha2 VIETNAM()
 * @method static CountryAlpha2 WALLIS_FUTUNA()
 * @method static CountryAlpha2 WESTERN_SAHARA()
 * @method static CountryAlpha2 YEMEN()
 * @method static CountryAlpha2 ZAMBIA()
 * @method static CountryAlpha2 ZIMBABWE()
 */
class CountryAlpha2 extends Enum
{
    private const AFGHANISTAN = 'AF';
    private const AALAND_ISLANDS = 'AX';
    private const ALBANIA = 'AL';
    private const ALGERIA = 'DZ';
    private const AMERICAN_SAMOA = 'AS';
    private const ANDORRA = 'AD';
    private const ANGOLA = 'AO';
    private const ANGUILLA = 'AI';
    private const ANTARCTICA = 'AQ';
    private const ANTIGUA_BARBUDA = 'AG';
    private const ARGENTINA = 'AR';
    private const ARMENIA = 'AM';
    private const ARUBA = 'AW';
    private const AUSTRALIA = 'AU';
    private const AUSTRIA = 'AT';
    private const AZERBAIJAN = 'AZ';
    private const BAHAMAS = 'BS';
    private const BAHRAIN = 'BH';
    private const BANGLADESH = 'BD';
    private const BARBADOS = 'BB';
    private const BELARUS = 'BY';
    private const BELGIUM = 'BE';
    private const BELIZE = 'BZ';
    private const BENIN = 'BJ';
    private const BERMUDA = 'BM';
    private const BHUTAN = 'BT';
    private const BOLIVIA = 'BO';
    private const BOSNIA_HERZEGOVINA = 'BA';
    private const BOTSWANA = 'BW';
    private const BOUVET_ISLAND = 'BV';
    private const BRAZIL = 'BR';
    private const BRITISH_INDIAN_OCEAN_TERRITORY = 'IO';
    private const BRITISH_VIRGIN_ISLANDS = 'VG';
    private const BRUNEI = 'BN';
    private const BULGARIA = 'BG';
    private const BURKINA_FASO = 'BF';
    private const BURUNDI = 'BI';
    private const CAMBODIA = 'KH';
    private const CAMEROON = 'CM';
    private const CANADA = 'CA';
    private const CAPE_VERDE = 'CV';
    private const CARIBBEAN_NETHERLANDS = 'BQ';
    private const CAYMAN_ISLANDS = 'KY';
    private const CENTRAL_AFRICAN_REPUBLIC = 'CF';
    private const CHAD = 'TD';
    private const CHILE = 'CL';
    private const CHINA = 'CN';
    private const CHRISTMAS_ISLAND = 'CX';
    private const COCOS_KEELING_ISLANDS = 'CC';
    private const COLOMBIA = 'CO';
    private const COMOROS = 'KM';
    private const CONGO_BRAZZAVILLE = 'CG';
    private const CONGO_KINSHASA = 'CD';
    private const COOK_ISLANDS = 'CK';
    private const COSTA_RICA = 'CR';
    private const COTE_D_IVOIRE = 'CI';
    private const CROATIA = 'HR';
    private const CUBA = 'CU';
    private const CURACAO = 'CW';
    private const CYPRUS = 'CY';
    private const CZECHIA = 'CZ';
    private const DENMARK = 'DK';
    private const DJIBOUTI = 'DJ';
    private const DOMINICA = 'DM';
    private const DOMINICAN_REPUBLIC = 'DO';
    private const ECUADOR = 'EC';
    private const EGYPT = 'EG';
    private const EL_SALVADOR = 'SV';
    private const EQUATORIAL_GUINEA = 'GQ';
    private const ERITREA = 'ER';
    private const ESTONIA = 'EE';
    private const ESWATINI = 'SZ';
    private const ETHIOPIA = 'ET';
    private const FALKLAND_ISLANDS = 'FK';
    private const FAROE_ISLANDS = 'FO';
    private const FIJI = 'FJ';
    private const FINLAND = 'FI';
    private const FRANCE = 'FR';
    private const FRENCH_GUIANA = 'GF';
    private const FRENCH_POLYNESIA = 'PF';
    private const FRENCH_SOUTHERN_TERRITORIES = 'TF';
    private const GABON = 'GA';
    private const GAMBIA = 'GM';
    private const GEORGIA = 'GE';
    private const GERMANY = 'DE';
    private const GHANA = 'GH';
    private const GIBRALTAR = 'GI';
    private const GREECE = 'GR';
    private const GREENLAND = 'GL';
    private const GRENADA = 'GD';
    private const GUADELOUPE = 'GP';
    private const GUAM = 'GU';
    private const GUATEMALA = 'GT';
    private const GUERNSEY = 'GG';
    private const GUINEA = 'GN';
    private const GUINEA_BISSAU = 'GW';
    private const GUYANA = 'GY';
    private const HAITI = 'HT';
    private const HEARD_MCDONALD_ISLANDS = 'HM';
    private const HONDURAS = 'HN';
    private const HONG_KONG_SAR_CHINA = 'HK';
    private const HUNGARY = 'HU';
    private const ICELAND = 'IS';
    private const INDIA = 'IN';
    private const INDONESIA = 'ID';
    private const IRAN = 'IR';
    private const IRAQ = 'IQ';
    private const IRELAND = 'IE';
    private const ISLE_OF_MAN = 'IM';
    private const ISRAEL = 'IL';
    private const ITALY = 'IT';
    private const JAMAICA = 'JM';
    private const JAPAN = 'JP';
    private const JERSEY = 'JE';
    private const JORDAN = 'JO';
    private const KAZAKHSTAN = 'KZ';
    private const KENYA = 'KE';
    private const KIRIBATI = 'KI';
    private const KUWAIT = 'KW';
    private const KYRGYZSTAN = 'KG';
    private const LAOS = 'LA';
    private const LATVIA = 'LV';
    private const LEBANON = 'LB';
    private const LESOTHO = 'LS';
    private const LIBERIA = 'LR';
    private const LIBYA = 'LY';
    private const LIECHTENSTEIN = 'LI';
    private const LITHUANIA = 'LT';
    private const LUXEMBOURG = 'LU';
    private const MACAO_SAR_CHINA = 'MO';
    private const MADAGASCAR = 'MG';
    private const MALAWI = 'MW';
    private const MALAYSIA = 'MY';
    private const MALDIVES = 'MV';
    private const MALI = 'ML';
    private const MALTA = 'MT';
    private const MARSHALL_ISLANDS = 'MH';
    private const MARTINIQUE = 'MQ';
    private const MAURITANIA = 'MR';
    private const MAURITIUS = 'MU';
    private const MAYOTTE = 'YT';
    private const MEXICO = 'MX';
    private const MICRONESIA = 'FM';
    private const MOLDOVA = 'MD';
    private const MONACO = 'MC';
    private const MONGOLIA = 'MN';
    private const MONTENEGRO = 'ME';
    private const MONTSERRAT = 'MS';
    private const MOROCCO = 'MA';
    private const MOZAMBIQUE = 'MZ';
    private const MYANMAR_BURMA = 'MM';
    private const NAMIBIA = 'NA';
    private const NAURU = 'NR';
    private const NEPAL = 'NP';
    private const NETHERLANDS = 'NL';
    private const NEW_CALEDONIA = 'NC';
    private const NEW_ZEALAND = 'NZ';
    private const NICARAGUA = 'NI';
    private const NIGER = 'NE';
    private const NIGERIA = 'NG';
    private const NIUE = 'NU';
    private const NORFOLK_ISLAND = 'NF';
    private const NORTH_KOREA = 'KP';
    private const NORTH_MACEDONIA = 'MK';
    private const NORTHERN_MARIANA_ISLANDS = 'MP';
    private const NORWAY = 'NO';
    private const OMAN = 'OM';
    private const PAKISTAN = 'PK';
    private const PALAU = 'PW';
    private const PALESTINIAN_TERRITORIES = 'PS';
    private const PANAMA = 'PA';
    private const PAPUA_NEW_GUINEA = 'PG';
    private const PARAGUAY = 'PY';
    private const PERU = 'PE';
    private const PHILIPPINES = 'PH';
    private const PITCAIRN_ISLANDS = 'PN';
    private const POLAND = 'PL';
    private const PORTUGAL = 'PT';
    private const PUERTO_RICO = 'PR';
    private const QATAR = 'QA';
    private const REUNION = 'RE';
    private const ROMANIA = 'RO';
    private const RUSSIA = 'RU';
    private const RWANDA = 'RW';
    private const SAMOA = 'WS';
    private const SAN_MARINO = 'SM';
    private const SAO_TOME_PRINCIPE = 'ST';
    private const SAUDI_ARABIA = 'SA';
    private const SENEGAL = 'SN';
    private const SERBIA = 'RS';
    private const SEYCHELLES = 'SC';
    private const SIERRA_LEONE = 'SL';
    private const SINGAPORE = 'SG';
    private const SINT_MAARTEN = 'SX';
    private const SLOVAKIA = 'SK';
    private const SLOVENIA = 'SI';
    private const SOLOMON_ISLANDS = 'SB';
    private const SOMALIA = 'SO';
    private const SOUTH_AFRICA = 'ZA';
    private const SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS = 'GS';
    private const SOUTH_KOREA = 'KR';
    private const SOUTH_SUDAN = 'SS';
    private const SPAIN = 'ES';
    private const SRI_LANKA = 'LK';
    private const ST_BARTHELEMY = 'BL';
    private const ST_HELENA = 'SH';
    private const ST_KITTS_NEVIS = 'KN';
    private const ST_LUCIA = 'LC';
    private const ST_MARTIN = 'MF';
    private const ST_PIERRE_MIQUELON = 'PM';
    private const ST_VINCENT_GRENADINES = 'VC';
    private const SUDAN = 'SD';
    private const SURINAME = 'SR';
    private const SVALBARD_JAN_MAYEN = 'SJ';
    private const SWEDEN = 'SE';
    private const SWITZERLAND = 'CH';
    private const SYRIA = 'SY';
    private const TAIWAN = 'TW';
    private const TAJIKISTAN = 'TJ';
    private const TANZANIA = 'TZ';
    private const THAILAND = 'TH';
    private const TIMOR_LESTE = 'TL';
    private const TOGO = 'TG';
    private const TOKELAU = 'TK';
    private const TONGA = 'TO';
    private const TRINIDAD_TOBAGO = 'TT';
    private const TUNISIA = 'TN';
    private const TURKEY = 'TR';
    private const TURKMENISTAN = 'TM';
    private const TURKS_CAICOS_ISLANDS = 'TC';
    private const TUVALU = 'TV';
    private const U_S_OUTLYING_ISLANDS = 'UM';
    private const U_S_VIRGIN_ISLANDS = 'VI';
    private const UGANDA = 'UG';
    private const UKRAINE = 'UA';
    private const UNITED_ARAB_EMIRATES = 'AE';
    private const UNITED_KINGDOM = 'GB';
    private const UNITED_STATES = 'US';
    private const URUGUAY = 'UY';
    private const UZBEKISTAN = 'UZ';
    private const VANUATU = 'VU';
    private const VATICAN_CITY = 'VA';
    private const VENEZUELA = 'VE';
    private const VIETNAM = 'VN';
    private const WALLIS_FUTUNA = 'WF';
    private const WESTERN_SAHARA = 'EH';
    private const YEMEN = 'YE';
    private const ZAMBIA = 'ZM';
    private const ZIMBABWE = 'ZW';
}
